In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("weather1.csv")

In [5]:
df

           Day  Temperature   Wind Speed           Event
0   01-01-2018            35         320           Rainy
1   02-01-2018            28         123           cloud
2   03-01-2018            26         156             Hot
3   04-01-2018            29         174  not available
4   05-01-2018            30         185           Rainy
5   06-01-2018            31         169           cloud
6   07-01-2018            32         245             Hot
7   08-01-2018            35         123  not available
8   09-01-2018            40         156           cloud
9   10-01-2018            22         147             Hot
10  11-01-2018            35         563  not available
11  12-01-2018            28         156           cloud
12  13-01-2018            24         412             Hot
13  14-01-2018            26         457           Rainy
14  01-02-2018            32         423           cloud
15  02-02-2018            35         156             Hot
16  03-02-2018            36         148  not available
17  04-02-2018            37         175  not available
18  05-02-2018            35         245           Rainy
19  06-02-2018            22         265             Hot
20  07-02-2018            25         245             Hot
21  08-02-2018            29         231  not available
22  09-02-2018            30         269             Hot
23  10-02-2018            32         269           Rainy
24  11-02-2018            32         247           Rainy
25  01-03-2018            31         258           Rainy
26  02-03-2018            41         265           Rainy
27  03-03-2018            42         236             Hot
28  04-03-2018            43         254             Hot
29  05-03-2018            25         258           cloud
30  06-03-2018            28         236  not available
31  07-03-2018            21         254             NaN
32  08-03-2018            20         245           Rainy
33  09-03-2018            35         285           cloud
34  10-03-2018            45         269           cloud
35  01-04-2018            40         247           Rainy
36  02-04-2018            41         321           cloud
37  03-04-2018            32         321           cloud
38  04-04-2018            35         351           cloud
39  05-04-2018            22         302           cloud
40  06-04-2018            21         306  not available
41  07-04-2018            23         385  not available
42  08-04-2018            24         300  not available
43  09-04-2018            35         213  not available
44  10-04-2018            22         265  not available